### ISSUE TITLE
Link to file with multiple level 1 heading show as "ambiguous" 

### ISSUE THREAD

**Issue by Hirschiii** [artempyanykh/marksman#323]
I have the practise to set the title in the yaml-header and use multiple level one headings in the document. I pretty sure this is the issue, when I reduce the number of level one headings, the warning goes away. 

I did not find any setting like offsetting the heading by one, or even ignore this warning.

Is there a way to remove this warning?

Thank you very much, except of this I really do enjoy using this LSP

**Comment by bearv5** [comment]
The diagnostics function of marksman can be disabled directly if you doesn't mind the absence of marksman's other link diagnostics prompts. Such as:
```
-- in your nvim's config file
local lspconfig = require("lspconfig")
lspconfig.marksman.setup{
  handlers = {
    ["textDocument/publishDiagnostics"] = function() end
  }
}
```

**Comment by artempyanykh** [comment]
@Hirschiii this is something that came up a few times. I need to figure out how to make the UX consistent including how to tie this to the completion style, e.g.:
* when `completion.wiki.style = title-slug` Marksman would expect only a single level-1 header that is also the name of the doc,
* when completion style is file-based, it will only use file names and leave the headers to mark sections of the document.
* adding support for yaml front-matter as another source of 'titles' (as a feature it'll have to work with rename refactor)

Currently, Marksman uses both file names and level-1 headers to figure out the ID of a document, which I understand is suboptimal.

@bearv5 nice workaround!

**Comment by wardw** [comment]
I'm also in the club of using multiple level 1 headings in a markdown document.

I've set my config to

    [completion]
    wiki.style = "file-stem"

but I'm still getting "Ambiguous link to document" for any link to a file with more than one h1.  Am I misunderstanding this, or with "file-stem" a vanilla link such as `[[my doc]]` should unambiguously link to the _file_ `my doc.md` regardless of the heading content within the file?  I'm more than happy just to write `[[my doc#heading]]` for those times I want to link to a specific heading (which i also do, so love this flexible approach).

**Comment by artempyanykh** [comment]
@wardw I'm planning to make the `h1 header == title` configurable, starting with some preliminary work in #364. But I think in the next release, you'll be able to say in `.marksman.toml` something like:
```
[core]
title_from_heading = false
```

And then H1s will be treated like regular headings (it will also affect the default completion style for wiki links).

**Comment by artempyanykh** [comment]
I think this should be addressed in [2024-12-04](https://github.com/artempyanykh/marksman/releases/tag/2024-12-04). Please, report if something doesn't work as expected.

**Comment by nms-scribe** [comment]
I am still seeing these errors with 'title_from_heading' set to false. I'm using Kate on Arch Linux, with marksman 20241218 (at least that's what the package manager claims it is). I've created a simple project to test this, these are the files in the directory:

`A.md`
```
This is a link to [[B]]
```

`B.md`
```
# Part I

Lorem Ipsum

# Part II

Ipsum Lorem

```

`.marksman.toml`
```
[core]
title_from_heading = false

[code_action]
toc.enable = false
```

(That last configuration I put in to test that marksman was loading the configuration. Without it I have access to that code action in `B.md`.)
